<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>CodeMem.Extractor</RootNamespace>
    <OptionStrict>On</OptionStrict>
    <OptionExplicit>On</OptionExplicit>
    <OptionInfer>Off</OptionInfer>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Version>0.1.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CodeMem.Extraction\CodeMem.Extraction.vbproj" />
  </ItemGroup>

</Project>
