' File: BridgeToolDescriptions.vb
' Project: CodeMem.Bridging
' Description: The eight registered tool descriptions, the texts of contracts/tools.md §2 verbatim; a fact asserts every caveat phrase (FR-312).
' Author: RCH Automation LLC
' Created: 2026-09-15

''' <summary>
''' One constant per tool. The type_usages text says "before removing or renaming it" where the spec's prose says delete: the SQL gate scans
''' this project's literals for the word (contracts/tools.md §2 carries the same wording).
''' </summary>
Public Module BridgeToolDescriptions

    ''' <summary>solutions.</summary>
    Public Const Solutions As String = "Every solution in the CodeMem code map with its latest extraction run: key, name, repo root, last-seen path; outcome, schema and SDK version, source digest, commit and dirty state (unknown when there is no commit), start and finish, and the ten reconciliation counts. Read-only; the map's extractor is its only writer. Refuses by name when the bridge is unconfigured or the map is absent, not a map, at another schema version, or busy under an extraction. Call map_status to learn whether a run is current."

    ''' <summary>symbol_search.</summary>
    Public Const SymbolSearch As String = "Find symbols in the CodeMem code map by name and/or kind, scoped to a MemOS project (projectId — resolved through the code_map_solutions registry to every solution bound to that project) or to one map solution (solutionKey), optionally narrowed to one project row (projectSymbolId — the id of a project-kind row inside the scope; the filter narrows the rows and never changes what the total counts). The name matches case-insensitively anywhere in the symbol's name; kind is one of: namespace, class, module, structure, interface, enum, enum_member, delegate, method, constructor, property, field, event, project. Returns active symbols only, at most 200 declarations, always with the total matched and whether the result was truncated — narrow the filter rather than page. A file linked into several projects declares one symbol per project; such twins are presented as one declaration compiled into N projects, carrying every project's symbol id. A projectId with no registry row is not an error: the result says it searched nothing and why. Read-only."

    ''' <summary>symbol_detail.</summary>
    Public Const SymbolDetail As String = "One active symbol whole: its fields, every part that declares it (a partial class has several; the one containing the symbol's name is flagged; a project has none), and its outbound and inbound edges grouped under all eight verbs — part_of, calls, uses, implements, extends, imports, depends_on, handles — with an empty list meaning none. An outbound edge to a symbol outside the solution (framework, package) carries its doc-comment id and is marked external. When the declaration is compiled into several projects the header names every twin's id; the parts and edges are the requested id's own. Requires symbolId and exactly one of projectId or solutionKey; a symbol outside that scope, one that does not exist, and one that is retired are each refused by name. Read-only."

    ''' <summary>references.</summary>
    Public Const References As String = "Every recorded occurrence whose target is the given active symbol — resolved by the compiler's identity, not by matching text — with path, line, column, the verb, and the symbol it occurs in. Containment (part_of) is not a reference and is never included; use symbol_detail's inbound part_of for what a type contains. Does not show AddHandler … AddressOf wiring sites: the map records each one as the handler's own outbound handles edge, not as an occurrence targeting it — they appear in the handler's symbol_detail, under outbound handles. A field or property read or written by its bare name, and a method passed by a bare AddressOf, are recorded as calls occurrences and appear here (CodeMem 003). A bare-name use whose target lies outside the map (framework, package) is not recorded. A constructor call (New X(…)) targets the constructor, not the type: for everything the map records against a type — its constructors and members included — use type_usages. Returns every occurrence, uncapped. Takes a mapped symbol id only; external targets are not addressable here. Requires symbolId and exactly one of projectId or solutionKey. Read-only."

    ''' <summary>orphans.</summary>
    Public Const Orphans As String = "Active symbols in the CodeMem code map that no recorded reference reaches, scoped to a MemOS project (projectId, resolved through the registry) or to one map solution (solutionKey), optionally narrowed to one kind (kind) or to one project row within the scope (projectSymbolId — the id the result's byProject lists); a filter narrows the rows, it never changes what counts as an orphan, and the totals describe the narrowed set and state the filter. A reference is any edge except part_of (containment) from outside the symbol, and a reference to a member counts as a use of the type or module that contains it. A method wired by a Handles clause, and a member that implements an interface member, are not reported: the map cannot see event or interface dispatch. Fields and properties are examined: since CodeMem 003 the map records a field or property used by its bare name. Namespaces and projects are not examined, and every result names them: the map holds no namespace rows, and project rows are roots, unreferenced by construction. An orphan is a symbol with no recorded reference, not a verdict that it is dead. The result includes live code whose use the map cannot see: entry points (Main); test classes and test methods, and anything else found by reflection or attributes; Overrides members called through their base; InitializeComponent, called from a Designer form's compiler-generated constructor; constructors that exist only to prevent instantiation; a bare-name use whose target lies outside the map, which is not recorded; methods used only by AddressOf with a bare name; anything consumed from outside the solution, such as a library's public surface; and code generated outside the solution tree. It does not report a member referenced only by a sibling: a group that references only itself surfaces as its outermost unreferenced container plus any member nothing references. It does not report a contract that is implemented but never called. Returns every orphan, uncapped, with counts per declaring project and per kind. Read-only; the map's extractor is its only writer."

    ''' <summary>type_usages.</summary>
    Public Const TypeUsages As String = "Everything the CodeMem code map records against one type — class, module, structure, interface, enum or delegate — in one call: references to the type itself, calls to each of its constructors (New X(…) targets the constructor, so references on the type alone reads 0), calls and uses of each of its direct members, and every implements or extends edge pointing at it. Grouped by verb with counts, then the flat occurrence list; each occurrence names the symbol it actually targets (the type, a constructor or a member) and whether it comes from inside the type (a member calling a sibling). total counts every occurrence; fromOutside is the number to read before removing or renaming it. Resolved by the compiler's identity, uncapped, active symbols only; containment (part_of) is not a use. A symbolId that is not a type is refused by name — use references. Requires symbolId and exactly one of projectId or solutionKey. Read-only."

    ''' <summary>map_status.</summary>
    Public Const MapStatus As String = "For every solution the code_map_solutions registry binds to the CodeMem map: the commit and dirty flag its latest completed run recorded, what HEAD is now in the registered repository root, whether the tree is dirty, how many commits HEAD is past the recorded one, and one verdict by name: current, behind (by N, HEAD named), dirty (the tree has uncommitted or untracked changes), no_git (the root cannot be read as a repository, or the run recorded no commit), map_missing_solution (the registry binds an id the map does not hold), or diverged (the recorded commit is not an ancestor of HEAD; no count is claimed). Nothing is guessed: a repository the bridge cannot read says so. Registered solutions with no binding, and inactive rows, are listed without a verdict. Call this at session start and before relying on references, orphans or type_usages; an extraction is the remedy (the hook on a green build, or extract). Read-only."

    ''' <summary>extract.</summary>
    Public Const Extract As String = "Refreshes the CodeMem map by running the CodeMem extractor as a child process for one registered solution — named by solutionKey, or by a repoPath that lies under a registered repository root — or, with stale set to true, for every bound solution whose map_status is behind, dirty or diverged, in sequence, one run each. The solution key is always taken from the code_map_solutions registry; a path under no registered root, and a key with no active bound row, are refused by name and nothing runs. Gated: extract.enabled in bridge.config.json must be true (default false) — the automatic green-build trigger additionally needs extract.onGreenBuild. A refusal names the gate that stopped it. Returns the extractor's exit code, its summary or refusal line verbatim, and the published run's ten counts. The bridge never writes the map itself; the extractor is its only writer. Normally called by the green-build hook, not directly; a human runs extract with stale."

End Module
