' File: BridgeToolDescriptions.vb
' Project: CodeMem.Bridging
' Description: The eight registered tool descriptions, the texts of 005 contracts/tools.md §2 verbatim; facts assert every 004 caveat phrase and the absence of the registry vocabulary (FR-312, 005 FR-407).
' Author: RCH Automation LLC
' Created: 2026-09-15
'
' 2026-09-17 (feature 005, T016): every text revised to scope by solutionKey; map_status describes not_in_map; extract describes solutionPath
' and the not-in-map answer; none mentions projectId, a registry, code_map_solutions or a MemOS project.

''' <summary>
''' One constant per tool. The type_usages text says "before removing or renaming it" where the spec's prose says delete: the SQL gate scans
''' this project's literals for the word (contracts/tools.md §2 carries the same wording).
''' </summary>
Public Module BridgeToolDescriptions

    ''' <summary>solutions.</summary>
    Public Const Solutions As String = "Every solution in the CodeMem code map with its latest extraction run: key, name, repo root, last-seen path; outcome, schema and SDK version, source digest, commit and dirty state (unknown when there is no commit), start and finish, the ten reconciliation counts, and the number of restore warnings recorded on the run. Read-only; the map's extractor is its only writer. Refuses by name when the bridge is unconfigured or the map is absent, not a map, at another schema version, or busy under an extraction. Call map_status to learn whether a run is current."

    ''' <summary>symbol_search.</summary>
    Public Const SymbolSearch As String = "Find symbols in the CodeMem code map by name and/or kind within one map solution (solutionKey — exact; solutions lists the keys), optionally narrowed to one project row (projectSymbolId — the id of a project-kind row inside the solution; the filter narrows the rows and never changes what the total counts). The name matches case-insensitively anywhere in the symbol's name; kind is one of: namespace, class, module, structure, interface, enum, enum_member, delegate, method, constructor, property, field, event, project. Returns active symbols only, at most 200 declarations, always with the total matched and whether the result was truncated — narrow the filter rather than page. A file linked into several projects declares one symbol per project; such twins are presented as one declaration compiled into N projects, carrying every project's symbol id. This bridge scopes by solutionKey only. Read-only."

    ''' <summary>symbol_detail.</summary>
    Public Const SymbolDetail As String = "One active symbol whole: its fields, every part that declares it (a partial class has several; the one containing the symbol's name is flagged; a project has none), and its outbound and inbound edges grouped under all eight verbs — part_of, calls, uses, implements, extends, imports, depends_on, handles — with an empty list meaning none. An outbound edge to a symbol outside the solution (framework, package) carries its doc-comment id and is marked external. When the declaration is compiled into several projects the header names every twin's id; the parts and edges are the requested id's own. Requires symbolId and solutionKey; a symbol outside that scope, one that does not exist, and one that is retired are each refused by name. Read-only."

    ''' <summary>references.</summary>
    Public Const References As String = "Every recorded occurrence whose target is the given active symbol — resolved by the compiler's identity, not by matching text — with path, line, column, the verb, and the symbol it occurs in. Containment (part_of) is not a reference and is never included; use symbol_detail's inbound part_of for what a type contains. Does not show AddHandler … AddressOf wiring sites: the map records each one as the handler's own outbound handles edge, not as an occurrence targeting it — they appear in the handler's symbol_detail, under outbound handles. A field or property read or written by its bare name, and a method passed by a bare AddressOf, are recorded as calls occurrences and appear here (CodeMem 003). A bare-name use whose target lies outside the map (framework, package) is not recorded. A constructor call (New X(…)) targets the constructor, not the type: for everything the map records against a type — its constructors and members included — use type_usages. Returns every occurrence, uncapped. Takes a mapped symbol id only; external targets are not addressable here. Requires symbolId and solutionKey. Read-only."

    ''' <summary>orphans.</summary>
    Public Const Orphans As String = "Active symbols in the CodeMem code map that no recorded reference reaches, scoped to one map solution (solutionKey), optionally narrowed to one kind (kind) or to one project row within the solution (projectSymbolId — the id the result's byProject lists); a filter narrows the rows, it never changes what counts as an orphan, and the totals describe the narrowed set and state the filter. A reference is any edge except part_of (containment) from outside the symbol, and a reference to a member counts as a use of the type or module that contains it. A method wired by a Handles clause, and a member that implements an interface member, are not reported: the map cannot see event or interface dispatch. Fields and properties are examined: since CodeMem 003 the map records a field or property used by its bare name. Namespaces and projects are not examined, and every result names them: the map holds no namespace rows, and project rows are roots, unreferenced by construction. An orphan is a symbol with no recorded reference, not a verdict that it is dead. The result includes live code whose use the map cannot see: entry points (Main); test classes and test methods, and anything else found by reflection or attributes; Overrides members called through their base; InitializeComponent, called from a Designer form's compiler-generated constructor; constructors that exist only to prevent instantiation; a bare-name use whose target lies outside the map, which is not recorded; methods used only by AddressOf with a bare name; anything consumed from outside the solution, such as a library's public surface; and code generated outside the solution tree. It does not report a member referenced only by a sibling: a group that references only itself surfaces as its outermost unreferenced container plus any member nothing references. It does not report a contract that is implemented but never called. Returns every orphan, uncapped, with counts per declaring project and per kind. Read-only; the map's extractor is its only writer."

    ''' <summary>type_usages.</summary>
    Public Const TypeUsages As String = "Everything the CodeMem code map records against one type — class, module, structure, interface, enum or delegate — in one call: references to the type itself, calls to each of its constructors (New X(…) targets the constructor, so references on the type alone reads 0), calls and uses of each of its direct members, and every implements or extends edge pointing at it. Grouped by verb with counts, then the flat occurrence list; each occurrence names the symbol it actually targets (the type, a constructor or a member) and whether it comes from inside the type (a member calling a sibling). total counts every occurrence; fromOutside is the number to read before removing or renaming it. Resolved by the compiler's identity, uncapped, active symbols only; containment (part_of) is not a use. A symbolId that is not a type is refused by name — use references. Requires symbolId and solutionKey. Read-only."

    ''' <summary>map_status.</summary>
    Public Const MapStatus As String = "For every solution the CodeMem map holds: the commit and dirty flag its latest completed run recorded, what HEAD is now in the solution's repository root (the root the extractor scoped the run to; the solution file's directory when there was no repository), whether the tree is dirty, how many commits HEAD is past the recorded one, and one verdict by name: current, behind (by N, HEAD named), dirty (the tree has uncommitted or untracked changes), no_git (the root cannot be read as a repository, or the run recorded no commit), or diverged (the recorded commit is not an ancestor of HEAD; no count is claimed). Nothing is guessed: a repository the bridge cannot read says so. Also lists, as not_in_map, every directory an extract has refused as not in the map — a green build the hook observed in a repository the map does not hold, or a repoPath given directly — that no mapped root contains yet, with the solution file found there, the suggested key and the exact extract command that would add it; the bridge never adds a solution itself. Call this at session start and before relying on references, orphans or type_usages; an extraction is the remedy (the hook on a green build, or extract). Read-only."

    ''' <summary>extract.</summary>
    Public Const Extract As String = "Refreshes the CodeMem map by running the CodeMem extractor as a child process for one solution — named by solutionKey (the map's last-seen solution file is used; with solutionPath the file is given explicitly and the solution need not be in the map yet: that is how a solution is added, and how a solution is re-pointed at a moved or renamed file), or by a repoPath that lies under a mapped solution's root — or, with stale set to true, for every mapped solution whose map_status is behind, dirty or diverged, in sequence, one run each. A repoPath under no mapped root is answered not in the map with the command that adds it, and nothing runs; the bridge never chooses a key. Gated: extract.enabled in bridge.config.json must be true (default false) — the automatic green-build trigger additionally needs extract.onGreenBuild. A refusal names the gate that stopped it. Returns the extractor's exit code, its summary or refusal line verbatim, the published run's ten counts and its recorded restore warnings. The bridge never writes the map itself; the extractor is its only writer. Normally called by the green-build hook, not directly; a human runs extract with stale, or with solutionKey and solutionPath to add a solution."

End Module
